name: Dev CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-java@master
        with:
          java-version: 11
          distribution: zulu
      - name: Grant execution permission for gradlew
        run: chmod +x gradlew
      - name: Run tests
        run: ./gradlew test
